#pragma once
#include <string>
#include <unordered_map>

namespace weapon_icons {

// inline - static here gave every including TU its own map built at static-init
inline std::unordered_map<std::string, std::string> icon_table = {
 // Classic undefeated.ttf glyphs (ASCII). Source mapping: Titled-Gui-CS2.
    {"knife_ct",        "]"}, {"knife_t",        "["},
    {"deagle",          "A"}, {"elite",          "B"}, {"fiveseven",      "C"},
    {"glock",           "D"}, {"revolver",       "J"}, {"hkp2000",        "E"},
    {"p250",            "F"}, {"usp_silencer",   "G"}, {"tec9",           "H"},
    {"cz75a",           "I"}, {"mac10",          "K"}, {"ump45",          "L"},
    {"bizon",           "M"}, {"mp7",            "N"}, {"mp9",            "R"},
    {"p90",             "O"}, {"galilar",        "Q"}, {"famas",          "R"},
    {"m4a1_silencer",   "T"}, {"m4a1",           "S"}, {"aug",            "U"},
    {"sg556",           "V"}, {"ak47",           "W"}, {"g3sg1",          "X"},
    {"scar20",          "Y"}, {"awp",            "Z"}, {"ssg08",          "a"},
    {"xm1014",          "b"}, {"sawedoff",       "c"}, {"mag7",           "d"},
    {"nova",            "e"}, {"negev",          "f"}, {"m249",           "g"},
    {"taser",           "h"}, {"flashbang",      "i"}, {"hegrenade",      "j"},
    {"smokegrenade",    "k"}, {"molotov",        "l"}, {"decoy",          "m"},
    {"incgrenade",      "n"}, {"c4",             "o"},
 // aliases
    {"p2000",           "E"}, {"m4a4",           "S"}, {"galil",          "Q"},
    {"mp5sd",           "N"}, {"knife",          "["}, {"knife_bayonet",  "]"},
    {"knife_flip",      "]"}, {"knife_gut",      "]"}, {"knife_karambit", "]"},
    {"knife_m9_bayonet","]"}, {"knife_tactical", "]"}, {"knife_falchion", "]"},
    {"knife_survival_bowie", "]"}, {"knife_butterfly", "]"}, {"knife_push",  "]"},
    {"knife_cord",      "]"}, {"knife_canis",    "]"}, {"knife_ursus",    "]"},
    {"knife_gypsy_jackknife", "]"}, {"knife_outdoor", "]"}, {"knife_stiletto", "]"},
    {"knife_widowmaker","]"}, {"knife_skeleton", "]"}, {"knife_css",      "]"},
    {"knife_kukri",     "]"}, {"knife_twinblade","]"}, {"knife_gg",       "]"},
    {"shield",          ""},
};

static std::
unordered_map<std::
string, const char*> display_table = {
    {"deagle",          "Desert Eagle"},
    {"elite",           "Dual Berettas"},
    {"fiveseven",       "Five-SeveN"},
    {"glock",           "Glock-18"},
    {"ak47",            "AK-47"},
    {"aug",             "AUG"},
    {"awp",             "AWP"},
    {"famas",           "FAMAS"},
    {"g3sg1",           "G3SG1"},
    {"galilar",         "Galil AR"},
    {"m249",            "M249"},
    {"m4a1",            "M4A4"},
    {"mac10",           "MAC-10"},
    {"p90",             "P90"},
    {"mp5sd",           "MP5-SD"},
    {"ump45",           "UMP-45"},
    {"xm1014",          "XM1014"},
    {"bizon",           "PP-Bizon"},
    {"mag7",            "MAG-7"},
    {"negev",           "Negev"},
    {"sawedoff",        "Sawed-Off"},
    {"tec9",            "Tec-9"},
    {"taser",           "Zeus x27"},
    {"hkp2000",         "P2000"},
    {"mp7",             "MP7"},
    {"mp9",             "MP9"},
    {"nova",            "Nova"},
    {"p250",            "P250"},
    {"shield",          "Shield"},
    {"scar20",          "SCAR-20"},
    {"sg556",           "SG 553"},
    {"ssg08",           "SSG 08"},
    {"knife",           "Knife"},
    {"knife_gg",        "Knife"},
    {"flashbang",       "Flashbang"},
    {"hegrenade",       "HE Grenade"},
    {"smokegrenade",    "Smoke Grenade"},
    {"molotov",         "Molotov"},
    {"decoy",           "Decoy"},
    {"incgrenade",      "Incendiary"},
    {"c4",              "Bomb"},
    {"knife_t",         "Knife (T)"},
    {"m4a1_silencer",   "M4A1-S"},
    {"usp_silencer",    "USP-S"},
    {"cz75a",           "CZ75-Auto"},
    {"revolver",        "R8 Revolver"},
    {"knife_bayonet",   "Bayonet"},
    {"knife_css",       "Knife"},
    {"knife_flip",      "Flip Knife"},
    {"knife_gut",       "Gut Knife"},
    {"knife_karambit",  "Karambit"},
    {"knife_m9_bayonet","M9 Bayonet"},
    {"knife_tactical",  "Tactical Knife"},
    {"knife_falchion",  "Falchion Knife"},
    {"knife_survival_bowie", "Bowie Knife"},
    {"knife_butterfly", "Butterfly Knife"},
    {"knife_push",      "Shadow Daggers"},
    {"knife_cord",      "Cord Knife"},
    {"knife_canis",     "Canis Knife"},
    {"knife_ursus",     "Ursus Knife"},
    {"knife_gypsy_jackknife", "Jack Knife"},
    {"knife_outdoor",   "Outdoor Knife"},
    {"knife_stiletto",  "Stiletto Knife"},
    {"knife_widowmaker","Widowmaker Knife"},
    {"knife_skeleton",  "Skeleton Knife"},
};

}
